# fly.toml app configuration file generated for algorand-node on 2025-04-15T05:03:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'algorand-node'
primary_region = 'fra'

[experimental]
  cmd = ['/bin/bash', '/run.sh']

[build]
  image = 'algorand/algod:latest'

[[mounts]]
  source = 'node_vol'
  destination = '/algod/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '500GB'

[http_service]
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 4160

  [[services.ports]]
    port = 4160

[[files]]
  guest_path = '/run.sh'
  local_path = 'run.sh'

[[files]]
  guest_path = '/app/genesis.json'
  local_path = 'generated/genesis.json'

[[files]]
  guest_path = '/algod/data/algod.token'
  local_path = 'generated/algod.token'

[[vm]]
  size = 'performance-8x'
  memory = '16gb'
  cpu_kind = 'performance'
  cpus = 8
